V4: updated scripts

diff --git a/.config/hypr/scripts/chwp b/.config/hypr/scripts/chwp
--- a/.config/hypr/scripts/chwp
+++ b/.config/hypr/scripts/chwp
@@ -1,48 +1,63 @@
 #!/bin/bash
 
-# DEfault values
-reload=flase
-wallpaperPath=~/.config/hypr/wallpapers/wallpaper.png
-sddmpath=/usr/share/sddm/themes/sugar-candy/Backgrounds/Wallpaper.png
-filename=""
+# Default values
+reload=false
+wallpaperPath=~/.config/hypr/wallpaper
+sddmPath=/usr/share/sddm/themes/sugar-candy/Backgrounds/Wallpaper.png
 
+# Display help message
+display_help() {
+  echo "
+  Usage: $0 [-r] <filename>
+  Set a new wallpaper on the system using the swww command.
 
-if [ $# -eq 0 ]; then
-  echo "Usage: $0 [-r] <filename>"
+  Options:
+  -r          Reload the current wallpaper
+  -h          Display this help message
+
+  Arguments:
+  <filename>  Path to the image file to set as the wallpaper
+
+  Default Values:
+  Wallpaper Path: $wallpaperPath
+  SDDM Wallpaper Path: $sddmPath
+
+  Examples:
+  $0 -r        # Reload the current wallpaper
+  $0 image.jpg # Set 'image.jpg' as the new wallpaper
+  "
+}
+
+if [ "$#" -eq 0 ] || [ "$1" == "--help" ] ; then
+  display_help
   exit 1
 fi
 
-while getopts ":r" opt; do
+  while getopts ":rh" opt; do
   case ${opt} in
-    r) reload=true
-    ;;
-    \?) 
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-    ;;
+    r) reload=true ;;
+    h) display_help; exit 0 ;;
+    \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
   esac
 done
 
 # Shift command line arguments to get the filename
 shift $((OPTIND - 1))
 
-# Reload Wallpaper
-if [ "$reload" = true ]; then
-  swww img $wallpaperPath
-  echo "Wallpaper reladed"
-  exit 1
-fi
-
 # Check if file exists
-filename=$(readlink -f $1)
-if [ ! -f "$1" ]; then
+filename=$(readlink -f "${1:-}")
+if [ ! -f "$filename" ] && [ $reload = false ]; then
   echo "File not found."
   exit 1
 fi
 
-#set file as new wallpaper
-ln -sif $filename $wallpaperPath
-sudo cp $wallpaperPath $sddmpath
-swww img $wallpaperPath
-echo "new Wallpaper loaded"
+# Reload or set new wallpaper
+if [ "$reload" = true ]; then
+  swww img "$wallpaperPath"  --transition-type any
+  action="reloaded"
+else
+  cp "$filename" "$wallpaperPath" && action="loaded: "
+  swww img "$wallpaperPath" --transition-type any
+fi
 
+echo "Wallpaper $action$filename"
